apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
 
spec:
  selector:
    matchLabels:
      app: hasnaa
  
  replicas: 3
  template:
    metadata:
      name: my-web-app
      labels:
        app: hasnaa
    spec:
      containers:
        - name: my-nginx-app
          image: hasnaanagy/nginx-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
  strategy: 
    type: Recreate            